apiVersion: v1
kind: Service
metadata:
  name: product-service-service
spec:
  ports:
   - name: tcp
     port: 80
     protocol: TCP
     targetPort: 3504
  selector:
    app: product-service
  type: LoadBalancer
  loadBalancerIP: 192.168.1.14