apiVersion: v1
kind: Service
metadata:
  name: store-service-service
spec:
  ports:
   - name: tcp
     port: 80
     protocol: TCP
     targetPort: 3502
  selector:
    app: store-service
  type: LoadBalancer
  loadBalancerIP: 192.168.1.12