apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  USER_SERVICE_POSTGRESCONNECTION: ''
  USER_SERVICE_BIND_ADDRESS: '0.0.0.0:3501'
  USER_SERVICE_SESSIONSERVICEADDRESS: '192.168.1.35:80'