apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  USER_SERVICE_POSTGRES_CONNECTION: ''
  USER_SERVICE_BIND_ADDRESS: '0.0.0.0:3501'
  USER_SERVICE_SESSION_SERVICE_ADDRESS: '192.168.1.13:80'