apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/policy: "force"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: user-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service-deployment
        image: ryss/user-service:latest
        envFrom:
        - configMapRef:
            name: user-config
        imagePullPolicy: Always
        ports:
          - containerPort: 3501