// Code generated by protoc-gen-go. DO NOT EDIT.
// source: session_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSessionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{0}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateSessionResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{1}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifySessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySessionRequest) Reset()         { *m = VerifySessionRequest{} }
func (m *VerifySessionRequest) String() string { return proto.CompactTextString(m) }
func (*VerifySessionRequest) ProtoMessage()    {}
func (*VerifySessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{2}
}

func (m *VerifySessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySessionRequest.Unmarshal(m, b)
}
func (m *VerifySessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySessionRequest.Marshal(b, m, deterministic)
}
func (m *VerifySessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySessionRequest.Merge(m, src)
}
func (m *VerifySessionRequest) XXX_Size() int {
	return xxx_messageInfo_VerifySessionRequest.Size(m)
}
func (m *VerifySessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySessionRequest proto.InternalMessageInfo

func (m *VerifySessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *VerifySessionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type VerifySessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifySessionResponse) Reset()         { *m = VerifySessionResponse{} }
func (m *VerifySessionResponse) String() string { return proto.CompactTextString(m) }
func (*VerifySessionResponse) ProtoMessage()    {}
func (*VerifySessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{3}
}

func (m *VerifySessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifySessionResponse.Unmarshal(m, b)
}
func (m *VerifySessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifySessionResponse.Marshal(b, m, deterministic)
}
func (m *VerifySessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifySessionResponse.Merge(m, src)
}
func (m *VerifySessionResponse) XXX_Size() int {
	return xxx_messageInfo_VerifySessionResponse.Size(m)
}
func (m *VerifySessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifySessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifySessionResponse proto.InternalMessageInfo

type DeleteSessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionRequest) Reset()         { *m = DeleteSessionRequest{} }
func (m *DeleteSessionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionRequest) ProtoMessage()    {}
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{4}
}

func (m *DeleteSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionRequest.Unmarshal(m, b)
}
func (m *DeleteSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionRequest.Merge(m, src)
}
func (m *DeleteSessionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionRequest.Size(m)
}
func (m *DeleteSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionRequest proto.InternalMessageInfo

func (m *DeleteSessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteSessionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSessionResponse) Reset()         { *m = DeleteSessionResponse{} }
func (m *DeleteSessionResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteSessionResponse) ProtoMessage()    {}
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff25770e79caedc0, []int{5}
}

func (m *DeleteSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSessionResponse.Unmarshal(m, b)
}
func (m *DeleteSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSessionResponse.Marshal(b, m, deterministic)
}
func (m *DeleteSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSessionResponse.Merge(m, src)
}
func (m *DeleteSessionResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteSessionResponse.Size(m)
}
func (m *DeleteSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSessionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateSessionRequest)(nil), "pb.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "pb.CreateSessionResponse")
	proto.RegisterType((*VerifySessionRequest)(nil), "pb.VerifySessionRequest")
	proto.RegisterType((*VerifySessionResponse)(nil), "pb.VerifySessionResponse")
	proto.RegisterType((*DeleteSessionRequest)(nil), "pb.DeleteSessionRequest")
	proto.RegisterType((*DeleteSessionResponse)(nil), "pb.DeleteSessionResponse")
}

func init() {
	proto.RegisterFile("session_service.proto", fileDescriptor_ff25770e79caedc0)
}

var fileDescriptor_ff25770e79caedc0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4e, 0x2d, 0x2e,
	0xce, 0xcc, 0xcf, 0x8b, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xd2, 0xe7, 0x12, 0x71, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d,
	0x86, 0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe7, 0x62, 0x2f, 0x2d, 0x4e,
	0x2d, 0x8a, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71, 0x3d, 0x53,
	0x94, 0x74, 0xb9, 0x44, 0xd1, 0x34, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1,
	0x96, 0xe4, 0x67, 0xa7, 0xe6, 0x41, 0xd5, 0x43, 0x38, 0x4a, 0xae, 0x5c, 0x22, 0x61, 0xa9, 0x45,
	0x99, 0x69, 0x95, 0x68, 0xe6, 0x63, 0x55, 0x8d, 0x6c, 0x2b, 0x13, 0x8a, 0xad, 0xe2, 0x5c, 0xa2,
	0x68, 0xc6, 0x40, 0x6c, 0x05, 0x99, 0xef, 0x92, 0x9a, 0x93, 0x8a, 0xe1, 0x7e, 0xd2, 0xcd, 0x47,
	0x33, 0x06, 0x62, 0xbe, 0xd1, 0x65, 0x46, 0x2e, 0x3e, 0xa8, 0x58, 0x30, 0x24, 0xf0, 0x84, 0xec,
	0xb9, 0xd8, 0x20, 0x21, 0x20, 0x24, 0xa1, 0x57, 0x90, 0xa4, 0x87, 0x2d, 0xf8, 0xa4, 0x24, 0xb1,
	0xc8, 0x40, 0x5d, 0xcc, 0x00, 0x32, 0x00, 0xe2, 0x19, 0x88, 0x01, 0xd8, 0xc2, 0x07, 0x62, 0x00,
	0x76, 0x2f, 0x83, 0x0d, 0x80, 0xb8, 0x16, 0x62, 0x00, 0xb6, 0x00, 0x80, 0x18, 0x80, 0xd5, 0x4f,
	0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0x04, 0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x71, 0x09, 0x3e,
	0x10, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionServiceClient interface {
	Create(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	Verify(ctx context.Context, in *VerifySessionRequest, opts ...grpc.CallOption) (*VerifySessionResponse, error)
	Delete(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
}

type sessionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionServiceClient(cc grpc.ClientConnInterface) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) Create(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, "/pb.SessionService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Verify(ctx context.Context, in *VerifySessionRequest, opts ...grpc.CallOption) (*VerifySessionResponse, error) {
	out := new(VerifySessionResponse)
	err := c.cc.Invoke(ctx, "/pb.SessionService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) Delete(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, "/pb.SessionService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
type SessionServiceServer interface {
	Create(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	Verify(context.Context, *VerifySessionRequest) (*VerifySessionResponse, error)
	Delete(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
}

// UnimplementedSessionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSessionServiceServer struct {
}

func (*UnimplementedSessionServiceServer) Create(ctx context.Context, req *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSessionServiceServer) Verify(ctx context.Context, req *VerifySessionRequest) (*VerifySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (*UnimplementedSessionServiceServer) Delete(ctx context.Context, req *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Create(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Verify(ctx, req.(*VerifySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SessionService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).Delete(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SessionService_Create_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _SessionService_Verify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SessionService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session_service.proto",
}
