// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store_product.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreProduct_Quantity int32

const (
	StoreProduct_NONE  StoreProduct_Quantity = 0
	StoreProduct_EMPTY StoreProduct_Quantity = 1
	StoreProduct_LOW   StoreProduct_Quantity = 2
	StoreProduct_HIGH  StoreProduct_Quantity = 3
)

var StoreProduct_Quantity_name = map[int32]string{
	0: "NONE",
	1: "EMPTY",
	2: "LOW",
	3: "HIGH",
}

var StoreProduct_Quantity_value = map[string]int32{
	"NONE":  0,
	"EMPTY": 1,
	"LOW":   2,
	"HIGH":  3,
}

func (x StoreProduct_Quantity) String() string {
	return proto.EnumName(StoreProduct_Quantity_name, int32(x))
}

func (StoreProduct_Quantity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed8bc43cb011480c, []int{0, 0}
}

type StoreProduct struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId              string                `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	ProductId            string                `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity             StoreProduct_Quantity `protobuf:"varint,4,opt,name=quantity,proto3,enum=pb.StoreProduct_Quantity" json:"quantity,omitempty"`
	CreatedAt            *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StoreProduct) Reset()         { *m = StoreProduct{} }
func (m *StoreProduct) String() string { return proto.CompactTextString(m) }
func (*StoreProduct) ProtoMessage()    {}
func (*StoreProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed8bc43cb011480c, []int{0}
}

func (m *StoreProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreProduct.Unmarshal(m, b)
}
func (m *StoreProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreProduct.Marshal(b, m, deterministic)
}
func (m *StoreProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreProduct.Merge(m, src)
}
func (m *StoreProduct) XXX_Size() int {
	return xxx_messageInfo_StoreProduct.Size(m)
}
func (m *StoreProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreProduct.DiscardUnknown(m)
}

var xxx_messageInfo_StoreProduct proto.InternalMessageInfo

func (m *StoreProduct) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoreProduct) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *StoreProduct) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *StoreProduct) GetQuantity() StoreProduct_Quantity {
	if m != nil {
		return m.Quantity
	}
	return StoreProduct_NONE
}

func (m *StoreProduct) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.StoreProduct_Quantity", StoreProduct_Quantity_name, StoreProduct_Quantity_value)
	proto.RegisterType((*StoreProduct)(nil), "pb.StoreProduct")
}

func init() {
	proto.RegisterFile("store_product.proto", fileDescriptor_ed8bc43cb011480c)
}

var fileDescriptor_ed8bc43cb011480c = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0xdd, 0xb4, 0x5f, 0x93, 0x51, 0x4a, 0x18, 0x2f, 0x69, 0x41, 0x0c, 0x3d, 0xe5,
	0xb4, 0x85, 0x88, 0x07, 0x8f, 0x1e, 0x8a, 0x0d, 0x68, 0x5b, 0x63, 0x41, 0x3c, 0x95, 0xa4, 0xbb,
	0x96, 0x05, 0xeb, 0xae, 0xe9, 0xe4, 0xe0, 0x3f, 0x2f, 0x92, 0x4d, 0x22, 0x1e, 0xe7, 0xbd, 0xdf,
	0xbc, 0xc7, 0x83, 0x8b, 0x13, 0x99, 0x4a, 0xed, 0x6c, 0x65, 0x64, 0xbd, 0x27, 0x61, 0x2b, 0x43,
	0x06, 0xb9, 0x2d, 0xa7, 0x57, 0x07, 0x63, 0x0e, 0xef, 0x6a, 0xee, 0x94, 0xb2, 0x7e, 0x9b, 0x93,
	0x3e, 0xaa, 0x13, 0x15, 0x47, 0xdb, 0x42, 0xb3, 0x6f, 0x06, 0xe7, 0xcf, 0xcd, 0xf3, 0xa6, 0xfd,
	0xc5, 0x31, 0x70, 0x2d, 0x23, 0x16, 0xb3, 0x24, 0xc8, 0xb9, 0x96, 0x38, 0x01, 0xbf, 0x0d, 0xd7,
	0x32, 0xe2, 0x4e, 0x1d, 0xb9, 0x3b, 0x93, 0x78, 0x09, 0xd0, 0x35, 0x36, 0xa6, 0xe7, 0xcc, 0xa0,
	0x53, 0x32, 0x89, 0x37, 0xe0, 0x7f, 0xd6, 0xc5, 0x07, 0x69, 0xfa, 0x8a, 0x06, 0x31, 0x4b, 0xc6,
	0xe9, 0x44, 0xd8, 0x52, 0xfc, 0x6d, 0x13, 0x4f, 0x1d, 0x90, 0xff, 0xa2, 0x78, 0x0b, 0xb0, 0xaf,
	0x54, 0x41, 0x4a, 0xee, 0x0a, 0x8a, 0x86, 0x31, 0x4b, 0xce, 0xd2, 0xa9, 0x68, 0x77, 0x88, 0x7e,
	0x87, 0xd8, 0xf6, 0x3b, 0xf2, 0xa0, 0xa3, 0xef, 0x68, 0x96, 0x82, 0xdf, 0x07, 0xa2, 0x0f, 0x83,
	0xd5, 0x7a, 0xb5, 0x08, 0xff, 0x61, 0x00, 0xc3, 0xc5, 0xe3, 0x66, 0xfb, 0x1a, 0x32, 0x1c, 0x81,
	0xf7, 0xb0, 0x7e, 0x09, 0x79, 0xe3, 0x2e, 0xb3, 0xfb, 0x65, 0xe8, 0x95, 0xff, 0x5d, 0xe4, 0xf5,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x1b, 0x59, 0xe3, 0x43, 0x01, 0x00, 0x00,
}
