// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Store struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName          string               `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Logo                 string               `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Location             *Location            `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Store) Reset()         { *m = Store{} }
func (m *Store) String() string { return proto.CompactTextString(m) }
func (*Store) ProtoMessage()    {}
func (*Store) Descriptor() ([]byte, []int) {
	return fileDescriptor_98bbca36ef968dfc, []int{0}
}

func (m *Store) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Store.Unmarshal(m, b)
}
func (m *Store) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Store.Marshal(b, m, deterministic)
}
func (m *Store) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Store.Merge(m, src)
}
func (m *Store) XXX_Size() int {
	return xxx_messageInfo_Store.Size(m)
}
func (m *Store) XXX_DiscardUnknown() {
	xxx_messageInfo_Store.DiscardUnknown(m)
}

var xxx_messageInfo_Store proto.InternalMessageInfo

func (m *Store) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Store) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Store) GetLogo() string {
	if m != nil {
		return m.Logo
	}
	return ""
}

func (m *Store) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Store) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Store)(nil), "pb.Store")
}

func init() {
	proto.RegisterFile("store.proto", fileDescriptor_98bbca36ef968dfc)
}

var fileDescriptor_98bbca36ef968dfc = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x31, 0x4f, 0x85, 0x30,
	0x14, 0x46, 0xd3, 0xfa, 0x9e, 0xf1, 0x5d, 0x08, 0x43, 0xa7, 0x86, 0x45, 0x74, 0x62, 0x2a, 0x89,
	0x4e, 0x8e, 0xee, 0xc6, 0x01, 0xdd, 0x49, 0x4b, 0x2b, 0x69, 0xd2, 0x72, 0x1b, 0xb8, 0x0e, 0xfe,
	0x2e, 0xff, 0xa0, 0xb1, 0xc0, 0xdb, 0xda, 0xef, 0x9c, 0xdc, 0x1c, 0x28, 0x56, 0xc2, 0xc5, 0xa9,
	0xb4, 0x20, 0xa1, 0xe0, 0xc9, 0xd4, 0x55, 0xc0, 0x51, 0x93, 0xc7, 0x79, 0xdb, 0xea, 0xfb, 0x09,
	0x71, 0x0a, 0xae, 0xcb, 0x3f, 0xf3, 0xfd, 0xd5, 0x91, 0x8f, 0x6e, 0x25, 0x1d, 0xd3, 0x26, 0x3c,
	0xfe, 0x32, 0x38, 0x7f, 0xfc, 0x1f, 0x11, 0x15, 0x70, 0x6f, 0x25, 0x6b, 0x58, 0x7b, 0xe9, 0xb9,
	0xb7, 0xe2, 0x01, 0x4a, 0xeb, 0xd7, 0x14, 0xf4, 0xcf, 0x30, 0xeb, 0xe8, 0x24, 0xcf, 0xa4, 0xd8,
	0xb7, 0x77, 0x1d, 0x9d, 0x10, 0x70, 0x0a, 0x38, 0xa1, 0xbc, 0xc9, 0x28, 0xbf, 0x45, 0x0b, 0x77,
	0x47, 0x83, 0x3c, 0x35, 0xac, 0x2d, 0x9e, 0x4a, 0x95, 0x8c, 0x7a, 0xdb, 0xb7, 0xfe, 0x4a, 0xc5,
	0x0b, 0xc0, 0xb8, 0x38, 0x4d, 0xce, 0x0e, 0x9a, 0xe4, 0x39, 0xbb, 0xb5, 0xda, 0x82, 0xd5, 0x11,
	0xac, 0x3e, 0x8f, 0xe0, 0xfe, 0xb2, 0xdb, 0xaf, 0x64, 0x6e, 0x33, 0x7e, 0xfe, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x77, 0x6a, 0x0c, 0x4a, 0x00, 0x01, 0x00, 0x00,
}
