name: CI

on: 
  push:
    paths:
      - 'src/go/user-service/**'
    #branches: 
    #  - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - uses: actions/setup-protoc@master
    
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel
    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

    - name: Install deps
      run: make go--deps
    - name: Build proto
      run: make go--genproto
    - name: Build project
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //src/go/user-service:user-service

    - name: Build docker image
      env:
        DOCKER_PASS: ${{ secrets.HUB_PASSWORD }}
        IMAGE: ryss/backend
      run: |
        echo 'Logging in to Docker Hub'
        docker login -u theleede -p $DOCKER_PASS
        echo 'Building Image'
        docker build -t ${IMAGE} . -f Dockerfile
        echo 'Tagging Image'
        docker tag ${IMAGE} ${IMAGE}:latest
        docker tag ${IMAGE} ${IMAGE}:${GITHUB_SHA::8}
        echo 'Pushing Image'
        docker push ${IMAGE}