apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service-deployment
  labels:
    keel.sh/trigger: poll
    keel.sh/match-tag: "true"
    keel.sh/policy: "force"
  annotations:
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: session-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: site
        image: ryss/session-service:latest
        envFrom:
        - configMapRef:
            name: session-config
        imagePullPolicy: Always
        ports:
          - containerPort: 3503